server:
  port: 8080

spring:
  application:
    name: agents-customes-tickets

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/agentscustomerstickets_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true}
    username: ${DB_USERNAME:agentscustomerstickets}
    password: ${DB_PASSWORD:agentscustomerstickets123}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

security:
  jwt:
    issuer: ${JWT_ISSUER:agents-customes-tickets}
    secret: ${JWT_SECRET:change-me-in-prod-change-me-in-prod-change-me}
    accessTokenMinutes: ${JWT_ACCESS_TOKEN_MINUTES:60}
