management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  endpoint:
    health:
      show-details: when_authorized
  metrics:
    tags:
      application: ${spring.application.name}
      app_instance: ${APP_INSTANCE:unknown}
    distribution:
      percentiles-histogram:
        http.server.requests: true
